### ISSUE TITLE
StartArrangingWithModelMessage is not implemented

### ISSUE THREAD

**Issue by MickVermeulen** [yuwui/Uchu#157]
The StartArrangingWithModelMessage should move the provided model to the TemporaryModels inventory and disassemble it, currently it's possible to have dupe rockets as this message is ignored so the active rocket isn't removed from the player inventory.

**Comment by MickVermeulen** [comment]
similar to #63

**Comment by teccheck** [comment]
I tried it using the the `InventoryManagerComponent.MoveItemBetweenInventoriesAsync` Method. The problem is, if I drop a rocket on the builder, the components of that rocket fly back into my inventory. I don't know why... 

Is there a listener on the Inventory that does that?

Edit: I found the "problem". It is in `Item.SetCountAsync`. This function disassembles the item into its parts.

**Comment by teccheck** [comment]
Does anyone know what happens if I press ESC, after putting a rocket into the builder (and changing it)? Right now you get the parts back into your inventory, but I guess you should get the rocket back how it was before editing it.
