### ISSUE TITLE
Bouncers sending players to wrong places

### ISSUE THREAD

**Issue by MustacheMan2** [yuwui/Uchu#172]
This is notable on the long distance bouncers in FV, there's a good chance it'll end up sending you into the void.

**Comment by TheNexusAvenger** [comment]
I was able to reproduce this on the `enhancement/reduce-load-time` branch with the bouncers that require smashing the Forbidden Valley statues with a Maelstrom Hammer. They were problematic if the statue wasn't smashed or was smashed after being built, but were fine if the statue was smashed and then the bouncer was built. Ideally, the bouncer should require the item to be smashed as part of another bug (https://github.com/UchuServer/Uchu/issues/60). To confirm, are you using the bouncers after smashing the statues?

**Comment by MustacheMan2** [comment]
The mission that gives out maelstrom hammers does not work, so no, I can't smash the statues!

**Comment by TheNexusAvenger** [comment]
Sounds like this issue is caused by 2 problems:
- The mission to get the Maelstrom hammer is non-functional. I was able to reproduce and had to use `/gmadditem 3014` to get a hammer.
- Quick builds that require objects to be smashed are always buildable. The bouncer fails if the statue is in the way, which it shouldn't. (https://github.com/UchuServer/Uchu/issues/60)
