### ISSUE TITLE
Softlock in Venture Explorer after completing Imagination collection mission

### ISSUE THREAD

**Issue by Ramen2X** [yuwui/Uchu#211]
In Venture Explorer, after completing the first Bob mission by gathering 6 imagination orbs, talking to him again will softlock your character (right after the animation for unlocking your imagination). Your cannot move your character, and the prompt for the next mission to talk to Sky Lane never appears. The only way you can get out of it is by respawning, however the mission progression then becomes messed up. If you go to Sky Lane in this state, she will not have a mission prompt for you.

As far as I can tell from old Uchu gameplay videos and other testing, this worked properly in the past.

Build: Latest Uchu 7d5a370 from dev branch. 
OS: Windows 10 Pro 20H2 64-bit.
LU Client: humanoid/lcdr's unpacked client (1.10.64)

**Comment by TheNexusAvenger** [comment]
~~This may actually be fixed on `enhancement/sub-missions` (https://github.com/UchuServer/Uchu/pull/209) because it makes some changes to missions are prioritized by ready to complete, active, and available in that order instead of the first one that matches one of the three. I'll test this in a few hours to check if it is fixed or not.~~

Edit: See below. Didn't know this was common.

**Comment by enteryournamehere** [comment]
I suspect this is caused by the standardscripts DLL not being specified in config.xml. Because of a change I made recently this entry isn't included in the automatically generated config.default.xml anymore. I'll make a commit to fix that soon, but to fix your issue, please make sure you have a `<ScriptDllSource>` entry under `<DllSource>` in your config.xml, with as value the path to Uchu.StandardScripts/bin/Debug/netcoreapp3.1/Uchu.StandardScripts.dll (absolute path or relative to the folder from where you run the server).

**Comment by MickVermeulen** [comment]
Like @enteryournamehere said, this is caused by invalid settings, make sure your standard scripts path is correct, this is a very common issue.

**Comment by Ramen2X** [comment]
Can confirm it works with ScriptDLLSource added. Thanks for letting me know!
