### ISSUE TITLE
Two Windows Open And Immediately Close 

### ISSUE THREAD

**Issue by RunningPlasmaDog** [yuwui/Uchu#26]
I am trying to update to the most recent version of Uchu. I have followed the steps with the config file. However, when I open Uchu.Master.exe it opens two windows and immediately closes them. I have tried specifying a different character port like the readme says but it does not fix the issue.

**Comment by Jettford** [comment]
Could you please look around for very common errors instead of immediately posting on Github the solution for the following is to head into your config find where it reads `Uchu.Instance` and `Uchu.StandardScripts`  in side the DLLSources and replace them with `../../../../Uchu.Instance/bin/debug/netcoreapp3.1/Uchu.Instance.dll` and `../../../../Uchu.StandardScripts/bin/debug/netcoreapp3.1/Uchu.StandardScripts` respectively and instead of running the EXE I normally have better luck with the DLL so I would run with a console ( Shift + Right Click and then click open with powershell or command prompt) `dotnet ./Uchu.Master.dll` . And also could you please contact me on Discord if you need anymore help if you think it may actually be a bug feel free (I don't own this repo its Yui's so you don't have to listen to me) but to try and not flood the errors please try and message me first. (My Discord is Encry#8175)

**Comment by RunningPlasmaDog** [comment]
Worked closing issue
