### ISSUE TITLE
not sure what im doing wrong. me idiot

### ISSUE THREAD

**Issue by littledrew22** [yuwui/Uchu#336]
first config try
![1crashconfig](https://user-images.githubusercontent.com/68356436/169556068-3ad528d8-eb3e-46ef-8d41-d0522e38d5d9.PNG)
![1crash](https://user-images.githubusercontent.com/68356436/169556067-3f488a96-2212-4fcb-b9b2-5f6ffdc6b91f.PNG)
different config tries
![2crashconfig](https://user-images.githubusercontent.com/68356436/169556064-c23b7a38-b88d-4509-a7c7-3447df210314.PNG)
![2crash](https://user-images.githubusercontent.com/68356436/169556070-a6188fbf-8d09-4b43-ba6c-59225cb5b539.PNG)

**Comment by TheNexusAvenger** [comment]
The first configuration has issues because it is incomplete XML. In XML, a "tag" such as `<x>` needs a corresponding closing tag `</x>`, which is missing. Notice how the second configuration has `</GameResourceFolder>`.

For both of them, the value for the game resource folder. If you are using Nexus LU Launcher, it will be `C:\Users\YOUR_USERNAME\.nlul\Client\res` on Windows. It appears you are based on the "Nexus-LU-Launcher.exe" faintly visible and the output, but the client is "packed" instead of "unpacked". Unpacked clients are larger and have all the resources split into their original files instead of packed into larger resource files. The easier method to resolve this is to delete your existing client and re-download an unpacked client.

**Comment by littledrew22** [comment]
i just moved the client to that folder while editing the xml and it worked like a charm
i guess it just dont like installs on drives other than C
thanks for your time
